# Generated by Django 5.2.12 on 2026-03-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('cognoms', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('carrec', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['cognoms', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Recurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=150)),
                ('descripcio', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('article', 'Article'), ('video', 'Vídeo'), ('podcast', 'Podcast'), ('curs', 'Curs'), ('guia', 'Guia')], max_length=20)),
                ('data_publicacio', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='catalog.autor')),
            ],
            options={
                'ordering': ['titol'],
            },
        ),
    ]
